### PR TITLE
Add status attribute + other minor fixes

### LINKED ISSUE #116: Add status attribute
There is no current way to track if a customer requires follow-up action from an agent.

Adding this attribute is the next logical step towards tracking this workflow.

### PR DESCRIPTION
**Pull request by ZShunRen**
There is no way to indicate if follow-up action is needed for a
particular customer, which is usually the case with financial services.

Adding the status attribute helps the user differentiate between clients
who may need follow-up action, and works in tandem with remark, where
case details can be inserted.

Other small changes include:
- Refactoring `Person::isSamePerson` method to use name, phone and email as
  checks for equality.
- Refactoring `Person::equals` method to use `Person::isSamePerson`
  method when checking for equality, which makes the code more
  maintainable as equality logic is only specified once.
- Added more tests into `AddCommandParser.java` to test the new flags like income, etc.
- Refactoring one of the tests in `AddCommandParserTest` which used a normal set, which did not preserve the order of duplicates, to a linked set which preserves order.
  
  Closes #116.

### CODE REVIEW

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 1]
```diff
@@ -39,7 +40,9 @@ public class PersonCard extends UiPart<Region> {
     @FXML
     private Label remark;
     @FXML
-    private FlowPane assignedTier;
+    private FlowPane assignedStatus;
```
Comment (FionaQY) [inline src/main/java/seedu/address/ui/PersonCard.java:43]: Is there a need for both assignedStatus and assignedStatusAndTier ?

File: src/main/java/seedu/address/storage/JsonAdaptedStatus.java [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    /**
+     * Constructs a {@code JsonAdaptedTag} with the given {@code status}.
+     */
+    @JsonCreator
+    public JsonAdaptedStatus(String status) {
+        this.status = status;
+    }
+
+    /**
+     * Converts a given {@code Tier} into this class for Jackson use.
```
Comment (FionaQY) [inline src/main/java/seedu/address/storage/JsonAdaptedStatus.java:25]: should this be {@code Status} instead?

File: src/main/java/seedu/address/storage/JsonAdaptedStatus.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+        return status;
+    }
+
+    @Override
+    public String toString() {
+        return status;
+    }
+
+    /**
+     * Converts this Jackson-friendly adapted tier object into the model's {@code Status} object.
```
Comment (FionaQY) [inline src/main/java/seedu/address/storage/JsonAdaptedStatus.java:42]: should this be "adapted tier" instead?

**Review by FionaQY — APPROVED** [review]
LGTM. Though I'm not sure if JsonAdaptedStatus/JsonAdaptedTier is needed given that a person can have at most one of which. 

I'm also not sure if Status should be its own status package either (though the same can be said for Tier)

File: src/main/java/seedu/address/ui/PersonCard.java (hunk 1 above)
Comment (ZShunRen) [reply src/main/java/seedu/address/ui/PersonCard.java:43]: Thank you for spotting this, I have amended it accordingly.

File: src/main/java/seedu/address/storage/JsonAdaptedStatus.java (hunk 3 above)
Comment (ZShunRen) [reply src/main/java/seedu/address/storage/JsonAdaptedStatus.java:42]: Thank you, I have amended it.

File: src/main/java/seedu/address/storage/JsonAdaptedStatus.java [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+    /**
+     * Constructs a {@code JsonAdaptedTag} with the given {@code status}.
+     */
+    @JsonCreator
+    public JsonAdaptedStatus(String status) {
+        this.status = status;
+    }
+
+    /**
+     * Converts a given {@code Status} into this class for Jackson use.
```
Comment (itsme-zeix) [inline src/main/java/seedu/address/storage/JsonAdaptedStatus.java:25]:
```suggestion
     * Converts a given {@code Status} into a {@code JsonAdaptedStatus} for Jackson use.
```
This works better for method hints when using this method in other classes.

File: src/main/java/seedu/address/ui/PersonCard.java [hunk 5]
```diff
@@ -39,7 +40,7 @@ public class PersonCard extends UiPart<Region> {
     @FXML
     private Label remark;
     @FXML
-    private FlowPane assignedTier;
+    private FlowPane assignedStatusAndTier;
```
Comment (itsme-zeix) [inline src/main/java/seedu/address/ui/PersonCard.java:43]:
```suggestion
    private FlowPane assignedTier
    @FXML
    private FlowPane assignedStatus
```
Perhaps we can isolate the logic if possible and make the appropriate changes in the CSS file, which would improve maintainability. Feel free to keep it as is if there are issues related to difficult UI logic.

**Review by itsme-zeix — APPROVED** [review]
Nice work overall! Great catch and change regarding the iincorrect plural form for Tier.

File: src/main/java/seedu/address/ui/PersonCard.java (hunk 5 above)
Comment (ZShunRen) [reply src/main/java/seedu/address/ui/PersonCard.java:43]: Hmm i'll try to refactor it, it's just that it may appear vertically instead of horizontally side by side.

File: src/main/java/seedu/address/model/status/Status.java [hunk 6]
```diff
@@ -0,0 +1,89 @@
...
+        } else {
+            this.status = StatusEnum.valueOf(statusString.toUpperCase());
+        }
+    }
+
+    /**
+     * Returns true if a given string is a valid status value.
+     *
+     * @param test The string to be tested
+     */
```
Comment (iamdiluxedbutcooler) [inline src/main/java/seedu/address/model/status/Status.java:36]: Would be better to have `@return` tag in the Javadoc comment and explaination of what boolean return value means :D

File: src/main/java/seedu/address/model/status/Status.java [hunk 7]
```diff
@@ -0,0 +1,89 @@
...
+    /**
+     * Formats the status into a string form, without square brackets.
+     * @return The string value of the status without brackets
+     */
+    public String toParsableString() {
+        return status.toString();
+    }
+
+    /**
+     * Represent what values Status can take.
```
Comment (iamdiluxedbutcooler) [inline src/main/java/seedu/address/model/status/Status.java:82]: Consider moving the enum to its own file if it might need to be referenced independently 👍🏻 This can be applied to other enums in our project too!

File: src/main/java/seedu/address/model/status/Status.java [hunk 8]
```diff
@@ -0,0 +1,89 @@
...
+        if (!(other instanceof Status)) {
+            return false;
+        }
+
+        Status otherStatus = (Status) other;
+        return this.status.equals(otherStatus.status);
+    }
+
+    @Override
+    public int hashCode() {
```
Comment (iamdiluxedbutcooler) [inline src/main/java/seedu/address/model/status/Status.java:64]: Good that you don't forget to override hash code! :D

File: src/main/java/seedu/address/storage/JsonAdaptedStatus.java [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+     */
+    @JsonCreator
+    public JsonAdaptedStatus(String status) {
+        this.status = status;
+    }
+
+    /**
+     * Converts a given {@code Status} into a {@code JsonAdaptedStatus} for Jackson use.
+     */
+    public JsonAdaptedStatus(Status source) {
```
Comment (iamdiluxedbutcooler) [inline src/main/java/seedu/address/storage/JsonAdaptedStatus.java:27]: Consider adding null check for source parameter!

File: src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java [hunk 10]
```diff
@@ -39,8 +39,9 @@ public void execute_newPerson_success() {
     }
 
     @Test
-    public void execute_newPersonWithTierAndRemark_success() {
-        Person validPerson = new PersonBuilder().withTier("GOLD").withRemark("big brained").build();
+    public void execute_newPersonWithTierAndRemarkAndStatus_success() {
+        Person validPerson =
+                new PersonBuilder().withTier("GOLD").withRemark("big brained").withStatus("urgent").build();
```
Comment (iamdiluxedbutcooler) [inline src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java:44]: Good that you not forget to test the status attributes in person!

**Review by iamdiluxedbutcooler — APPROVED** [review]
LGTM! Solid work for our new function status! Further improvement or supplement to this can be more test specifically on status, but for now the testing protocol for status under related command should be enough to cover most cases now. 🤩

File: src/main/java/seedu/address/storage/JsonAdaptedStatus.java (hunk 4 above)
Comment (ZShunRen) [reply src/main/java/seedu/address/storage/JsonAdaptedStatus.java]: Hi I have resolved this thanks.

File: src/main/java/seedu/address/model/status/Status.java (hunk 6 above)
Comment (ZShunRen) [reply src/main/java/seedu/address/model/status/Status.java:36]: Hi I have added this, thank you pleng.

File: src/main/java/seedu/address/model/status/Status.java (hunk 7 above)
Comment (ZShunRen) [reply src/main/java/seedu/address/model/status/Status.java:82]: I think for now since the enum is related to Status, we can keep it here, but we can possibly refactor the enums to CommandCommons to reduce coupling in the future.

File: src/main/java/seedu/address/storage/JsonAdaptedStatus.java (hunk 9 above)
Comment (ZShunRen) [reply src/main/java/seedu/address/storage/JsonAdaptedStatus.java:27]: Hi, will add the requirenonnull check!
