### PR TITLE
Add remark field to 'add' and 'edit' + minor fixes

### LINKED ISSUE #58: Refactor remark command into add and edit commands

### PR DESCRIPTION
**Pull request by ZShunRen**
Closes #58.

The remark command is the only way to add and edit remarks to a person. Using this separate command from `add` and `edit` is unintuitive and slows down users.

Adding the functionality of the `remark` command to `add` and `edit` will allow us to improve on these 2 aspects.

As of v1.3, the `add` and `edit` commands can be used to add a new remark, using the `rn/` flag. And for `edit` the `ra/` flag can be used to append a new remark onto existing remarks. These flags remain optional.

Aside from this the following minor changes are made:
- Add error message for concurrent `rn/` and `ra/` messages being specified in `Messages` class.
- Update format for the status bar message that is shown to users when a person is added or edited to include remark in `Messages` class.
- Add remark constraints message in `Remark` class.
- Add validity test for remark in `Remark` class.
- Add method to combine multiple remark in `Remark` class.

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/AddCommandParserTest.java [hunk 1]
```diff
@@ -101,7 +105,7 @@ public void parse_repeatedNonTagValue_failure() {
                 validExpectedPersonString + PHONE_DESC_AMY + EMAIL_DESC_AMY + NAME_DESC_AMY + ADDRESS_DESC_AMY
                         + validExpectedPersonString,
                 Messages.getErrorMessageForDuplicatePrefixes(PREFIX_NAME, PREFIX_ADDRESS, PREFIX_EMAIL, PREFIX_PHONE,
-                        PREFIX_JOB, PREFIX_INCOME));
+                        PREFIX_JOB, PREFIX_INCOME, PREFIX_TAG));
```
Comment (FionaQY) [inline src/test/java/seedu/address/logic/parser/AddCommandParserTest.java:108]: should PREFIX_NEW_REMARK or PREFIX_APPEND_REMARK be added as well?

File: src/test/java/seedu/address/logic/parser/EditCommandParserTest.java [hunk 2]
```diff
@@ -179,7 +179,7 @@ public void parse_multipleRepeatedFields_failure() {
                 + PHONE_DESC_BOB + ADDRESS_DESC_BOB + EMAIL_DESC_BOB + TAG_DESC_REJECT;
 
         assertParseFailure(parser, userInput,
-                Messages.getErrorMessageForDuplicatePrefixes(PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS));
+                Messages.getErrorMessageForDuplicatePrefixes(PREFIX_PHONE, PREFIX_EMAIL, PREFIX_ADDRESS, PREFIX_TAG));
```
Comment (FionaQY) [inline src/test/java/seedu/address/logic/parser/EditCommandParserTest.java:182]: ditto

File: src/test/java/seedu/address/testutil/PersonBuilder.java [hunk 3]
```diff
@@ -21,8 +21,8 @@ public class PersonBuilder {
     public static final String DEFAULT_ADDRESS = "123, Jurong West Ave 6, #08-111";
     public static final String DEFAULT_JOB = "Engineer";
     public static final int DEFAULT_INCOME = 0;
-    public static final String DEFAULT_TIER = "NA";
-    public static final String DEFAULT_REMARK = "";
+    public static final String DEFAULT_TIER = "REJECT";
```
Comment (FionaQY) [inline src/test/java/seedu/address/testutil/PersonBuilder.java:24]: is there a reason this is changed to reject?

**Review by FionaQY — APPROVED** [review]
LGTM

File: src/test/java/seedu/address/testutil/PersonBuilder.java (hunk 3 above)
Comment (ZShunRen) [reply src/test/java/seedu/address/testutil/PersonBuilder.java]: Hi I have since changed it to `NA` instead.

File: src/main/java/seedu/address/logic/parser/FilterCommandParser.java [hunk 4]
```diff
@@ -59,8 +59,8 @@ public FilterCommand parse(String args) throws ParseException {
             String substring = ParserUtil.parseAddress(argMultimap.getValue(PREFIX_ADDRESS).get()).value;
             return new FilterCommand(new AddressContainsSubstringPredicate(substring));
         }
-        if (argMultimap.getValue(PREFIX_REMARK).isPresent()) {
-            String substring = ParserUtil.parseAddress(argMultimap.getValue(PREFIX_REMARK).get()).value;
+        if (argMultimap.getValue(PREFIX_NEW_REMARK).isPresent()) {
+            String substring = ParserUtil.parseAddress(argMultimap.getValue(PREFIX_NEW_REMARK).get()).value;
```
Comment (itsme-zeix) [inline src/main/java/seedu/address/logic/parser/FilterCommandParser.java:63]: Filtering by the flag `rn/` instead of `r/` may result in user confusion, as `rn/` does not stand for `remark`, but `remark new` instead. Users may prefer to use `r/` as it is more intuitive for use with `filter`.

I understand your intention with the replacement though, as having a growing number of flags could make it harder for users to remember or differentiate between them.

Perhaps we could have internal discussion about this!

**Review by itsme-zeix — APPROVED** [review]
LGTM!
